'use client'

import { useState } from 'react'
import { FileText, Table, Share2, Download, CheckCircle2, Loader2 } from 'lucide-react'
import { getExportData, type DateRange } from '@/app/(app)/export/actions'
import { mp } from '@/lib/mixpanel'

const MOOD_LABELS = ['', 'Awful', 'Bad', 'Neutral', 'Good', 'Great']

const DATE_RANGES: { label: string; value: DateRange }[] = [
  { label: 'Last 7 days', value: '7d' },
  { label: 'Last 30 days', value: '30d' },
  { label: 'Last 3 months', value: '3m' },
  { label: 'All time', value: 'all' },
]

function formatDate(date: Date | null): string {
  if (!date) return 'N/A'
  return new Date(date).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
  })
}

function formatTime(date: Date | null): string {
  if (!date) return 'N/A'
  return new Date(date).toLocaleTimeString('en-US', {
    hour: '2-digit',
    minute: '2-digit',
  })
}

function avgMood(entries: { moodLevel: number }[]): string {
  if (entries.length === 0) return 'N/A'
  const avg = entries.reduce((sum, e) => sum + e.moodLevel, 0) / entries.length
  return avg.toFixed(1)
}

export function ExportClient() {
  const [dateRange, setDateRange] = useState<DateRange>('30d')
  const [generatingPdf, setGeneratingPdf] = useState(false)
  const [generatingCsv, setGeneratingCsv] = useState(false)
  const [pdfBlob, setPdfBlob] = useState<Blob | null>(null)
  const [csvContent, setCsvContent] = useState<string | null>(null)
  const [shareSuccess, setShareSuccess] = useState(false)

  const generatePdf = async () => {
    setGeneratingPdf(true)
    try {
      const data = await getExportData(dateRange)
      if (!data) return

      const { default: jsPDF } = await import('jspdf')
      const { default: autoTable } = await import('jspdf-autotable')

      const doc = new jsPDF()

      // Title
      doc.setFontSize(22)
      doc.setTextColor(125, 87, 0)
      doc.text('Moodify Wellness Report', 20, 25)

      // Subtitle
      doc.setFontSize(11)
      doc.setTextColor(159, 138, 106)
      const rangeLabel = DATE_RANGES.find((r) => r.value === dateRange)?.label ?? 'Custom'
      doc.text(`${rangeLabel} · Generated ${formatDate(data.exportedAt)}`, 20, 35)
      doc.text(`User: ${data.userName}`, 20, 43)

      // Summary
      doc.setFontSize(14)
      doc.setTextColor(80, 69, 52)
      doc.text('Summary', 20, 58)

      doc.setFontSize(10)
      doc.setTextColor(100, 90, 70)
      doc.text(`Total mood entries: ${data.moodEntries.length}`, 20, 67)
      doc.text(`Average mood: ${avgMood(data.moodEntries)} / 5`, 20, 75)
      doc.text(`Total assessments: ${data.assessments.length}`, 20, 83)

      let yPos = 95

      // Mood entries table
      if (data.moodEntries.length > 0) {
        doc.setFontSize(14)
        doc.setTextColor(80, 69, 52)
        doc.text('Mood Entries', 20, yPos)
        yPos += 8

        autoTable(doc, {
          startY: yPos,
          head: [['Date', 'Time', 'Mood', 'Level', 'Emotions', 'Activities', 'Note']],
          body: data.moodEntries.map((e) => [
            formatDate(e.loggedAt),
            formatTime(e.loggedAt),
            MOOD_LABELS[e.moodLevel] ?? '',
            String(e.moodLevel),
            e.emotions.join(', '),
            e.activities.join(', '),
            e.note?.substring(0, 50) ?? '',
          ]),
          styles: { fontSize: 8, cellPadding: 3 },
          headStyles: { fillColor: [229, 166, 35], textColor: [255, 255, 255] },
          alternateRowStyles: { fillColor: [249, 243, 227] },
          margin: { left: 20, right: 20 },
        })

        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        yPos = (doc as any).lastAutoTable.finalY + 15
      }

      // Assessments table
      if (data.assessments.length > 0 && yPos < 250) {
        doc.setFontSize(14)
        doc.setTextColor(80, 69, 52)
        doc.text('Assessment Results', 20, yPos)
        yPos += 8

        autoTable(doc, {
          startY: yPos,
          head: [['Date', 'Type', 'Score', 'Severity']],
          body: data.assessments.map((a) => [
            formatDate(a.takenAt),
            a.type === 'PHQ9' ? 'PHQ-9 (Depression)' : 'GAD-7 (Anxiety)',
            String(a.score),
            a.severityLabel,
          ]),
          styles: { fontSize: 9, cellPadding: 3 },
          headStyles: { fillColor: [125, 87, 0], textColor: [255, 255, 255] },
          alternateRowStyles: { fillColor: [249, 243, 227] },
          margin: { left: 20, right: 20 },
        })
      }

      // Footer disclaimer
      const pageCount = doc.getNumberOfPages()
      for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i)
        doc.setFontSize(8)
        doc.setTextColor(159, 138, 106)
        doc.text(
          'This is not a medical record. Generated by Moodify for personal use only. Not a clinical diagnosis.',
          20,
          doc.internal.pageSize.height - 10
        )
      }

      const blob = doc.output('blob')
      setPdfBlob(blob)

      // Download immediately
      const url = URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = `moodify-report-${dateRange}-${Date.now()}.pdf`
      a.click()
      URL.revokeObjectURL(url)

      mp.track('report_exported', { format: 'pdf', date_range: dateRange })
    } catch (err) {
      console.error('PDF generation error:', err)
    } finally {
      setGeneratingPdf(false)
    }
  }

  const generateCsv = async () => {
    setGeneratingCsv(true)
    try {
      const data = await getExportData(dateRange)
      if (!data) return

      const headers = ['date', 'time', 'mood_level', 'mood_label', 'emotions', 'activities', 'note']
      const rows = data.moodEntries.map((e) => [
        formatDate(e.loggedAt),
        formatTime(e.loggedAt),
        String(e.moodLevel),
        MOOD_LABELS[e.moodLevel] ?? '',
        `"${e.emotions.join('; ')}"`,
        `"${e.activities.join('; ')}"`,
        `"${(e.note ?? '').replace(/"/g, '""')}"`,
      ])

      const csv = [headers.join(','), ...rows.map((r) => r.join(','))].join('\n')
      setCsvContent(csv)

      const blob = new Blob([csv], { type: 'text/csv' })
      const url = URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = `moodify-data-${dateRange}-${Date.now()}.csv`
      a.click()
      URL.revokeObjectURL(url)

      mp.track('report_exported', { format: 'csv', date_range: dateRange })
    } catch (err) {
      console.error('CSV generation error:', err)
    } finally {
      setGeneratingCsv(false)
    }
  }

  const handleShare = async (format: 'pdf' | 'csv') => {
    try {
      if (format === 'pdf' && pdfBlob) {
        const file = new File([pdfBlob], `moodify-report-${dateRange}.pdf`, { type: 'application/pdf' })
        if (navigator.canShare?.({ files: [file] })) {
          await navigator.share({ files: [file], title: 'Moodify Wellness Report' })
          setShareSuccess(true)
          setTimeout(() => setShareSuccess(false), 2000)
        }
      } else if (format === 'csv' && csvContent) {
        const blob = new Blob([csvContent], { type: 'text/csv' })
        const file = new File([blob], `moodify-data-${dateRange}.csv`, { type: 'text/csv' })
        if (navigator.canShare?.({ files: [file] })) {
          await navigator.share({ files: [file], title: 'Moodify Data Export' })
          setShareSuccess(true)
          setTimeout(() => setShareSuccess(false), 2000)
        }
      }
    } catch (err) {
      if ((err as Error).name !== 'AbortError') {
        console.error('Share error:', err)
      }
    }
  }

  return (
    <div className="space-y-5">
      {/* Date range selector */}
      <div className="bg-[#f9f3e3] rounded-2xl p-5 border border-[#e8dcc8]">
        <h2 className="text-[15px] font-semibold text-[#7d5700] mb-3">Select Date Range</h2>
        <div className="flex flex-wrap gap-2">
          {DATE_RANGES.map((range) => (
            <button
              key={range.value}
              onClick={() => setDateRange(range.value)}
              className={`px-4 py-2 rounded-full text-[13px] font-medium transition-all min-h-[36px] ${
                dateRange === range.value
                  ? 'bg-[#7d5700] text-white shadow-sm'
                  : 'bg-white border border-[#e8dcc8] text-[#7d5700] hover:bg-[#f0e9d9]'
              }`}
            >
              {range.label}
            </button>
          ))}
        </div>
      </div>

      {/* What's included */}
      <div className="bg-[#f9f3e3] rounded-2xl p-5 border border-[#e8dcc8]">
        <h2 className="text-[15px] font-semibold text-[#7d5700] mb-3">What's included</h2>
        <ul className="space-y-2">
          {[
            'All mood entries with date, time, and level',
            'Emotion and activity tags for each entry',
            'Journal notes (PDF only)',
            'PHQ-9 and GAD-7 assessment results',
            'Severity scores and labels',
          ].map((item) => (
            <li key={item} className="flex items-center gap-2 text-[13px] text-[#504534]">
              <span className="size-1.5 rounded-full bg-[#e5a623] shrink-0" />
              {item}
            </li>
          ))}
        </ul>
      </div>

      {/* Export format cards */}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        {/* PDF */}
        <div className="bg-[#f9f3e3] rounded-2xl p-5 border border-[#e8dcc8]">
          <div className="flex items-center gap-3 mb-3">
            <div className="size-10 rounded-xl bg-[#EF4444]/10 flex items-center justify-center">
              <FileText className="size-5 text-[#dc2626]" />
            </div>
            <div>
              <h3 className="text-[15px] font-semibold text-[#7d5700]">PDF Report</h3>
              <p className="text-[12px] text-[#9e8a6a]">Formatted wellness report</p>
            </div>
          </div>
          <p className="text-[12px] text-[#9e8a6a] mb-4">
            A formatted report suitable for sharing with healthcare providers.
          </p>
          <button
            onClick={generatePdf}
            disabled={generatingPdf}
            className="w-full py-3 rounded-xl bg-[#dc2626] text-white text-[14px] font-semibold hover:bg-[#b91c1c] transition-colors min-h-[44px] flex items-center justify-center gap-2 disabled:opacity-60"
          >
            {generatingPdf ? (
              <>
                <Loader2 className="size-4 animate-spin" />
                Generating...
              </>
            ) : (
              <>
                <Download className="size-4" />
                Generate PDF
              </>
            )}
          </button>
          {pdfBlob && (
            <button
              onClick={() => handleShare('pdf')}
              className="w-full py-2.5 mt-2 rounded-xl border border-[#e8dcc8] text-[#7d5700] text-[13px] font-medium hover:bg-[#f0e9d9] transition-colors min-h-[44px] flex items-center justify-center gap-2"
            >
              {shareSuccess ? (
                <>
                  <CheckCircle2 className="size-4 text-[#22C55E]" />
                  Shared!
                </>
              ) : (
                <>
                  <Share2 className="size-4" />
                  Share PDF
                </>
              )}
            </button>
          )}
        </div>

        {/* CSV */}
        <div className="bg-[#f9f3e3] rounded-2xl p-5 border border-[#e8dcc8]">
          <div className="flex items-center gap-3 mb-3">
            <div className="size-10 rounded-xl bg-[#22C55E]/10 flex items-center justify-center">
              <Table className="size-5 text-[#16a34a]" />
            </div>
            <div>
              <h3 className="text-[15px] font-semibold text-[#7d5700]">CSV Data</h3>
              <p className="text-[12px] text-[#9e8a6a]">Raw data spreadsheet</p>
            </div>
          </div>
          <p className="text-[12px] text-[#9e8a6a] mb-4">
            Raw data in spreadsheet format, compatible with Excel and Google Sheets.
          </p>
          <button
            onClick={generateCsv}
            disabled={generatingCsv}
            className="w-full py-3 rounded-xl bg-[#16a34a] text-white text-[14px] font-semibold hover:bg-[#15803d] transition-colors min-h-[44px] flex items-center justify-center gap-2 disabled:opacity-60"
          >
            {generatingCsv ? (
              <>
                <Loader2 className="size-4 animate-spin" />
                Generating...
              </>
            ) : (
              <>
                <Download className="size-4" />
                Export CSV
              </>
            )}
          </button>
          {csvContent && (
            <button
              onClick={() => handleShare('csv')}
              className="w-full py-2.5 mt-2 rounded-xl border border-[#e8dcc8] text-[#7d5700] text-[13px] font-medium hover:bg-[#f0e9d9] transition-colors min-h-[44px] flex items-center justify-center gap-2"
            >
              <Share2 className="size-4" />
              Share CSV
            </button>
          )}
        </div>
      </div>

      {/* Disclaimer */}
      <div className="p-4 bg-[#f0e9d9] rounded-xl border border-[#e8dcc8]">
        <p className="text-[12px] text-[#9e8a6a] leading-relaxed text-center">
          This is not a medical record. Generated by Moodify for personal use only.
        </p>
      </div>
    </div>
  )
}
